apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: scot
  name: 'activemq'
  annotations: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: activemq
        deployment: activemq
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      volumes:
        - name: amq-scotaq-web-inf
          configMap:
            name: amq-scotaq-web-inf
        - name: amq-scotamq
          configMap:
            name: amq
        - name: amq-jetty
          configMap:
            name: amq
      containers:
        - name: activemq
          image: >-
            rmohr/activemq:5.15.9
          ports:
            - containerPort: 1883
              protocol: TCP
            - containerPort: 5672
              protocol: TCP
            - containerPort: 61613
              protocol: TCP
            - containerPort: 61614
              protocol: TCP
            - containerPort: 61616
              protocol: TCP
            - containerPort: 8161
              protocol: TCP
          volumeMounts:
            - name: amq-scotaq-web-inf
              mountPath: /opt/activemq/webapps/scot/WEB-INF/web.xml
              subPath: web.xml
            - name: amq-scotamq
              mountPath: /opt/activemq/conf/scotamq.xml
              subPath: scotamq.xml
            - name: amq-jetty
              mountPath: /opt/activemq/conf/jetty.xml
              subPath: jetty.xml
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          env: []
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 999
        fsGroup: 999
      schedulerName: default-scheduler  
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false