kind: ConfigMap
apiVersion: v1
metadata:
  name: amq-scotaq-web-inf
  namespace: scot
data:
  web.xml: |
    <!DOCTYPE web-app
        PUBLIC "-//Sun Microsystems, Inc.//DTD Web Application 2.3//EN"
        "http://java.sun.com/dtd/web-app_2_3.dtd">

    <web-app>

        <display-name>Apache ActiveMQ Web SCOT</display-name>

        <!-- context config -->
        <context-param>
            <param-name>org.apache.activemq.brokerURL</param-name>
            <param-value>vm://amq-broker</param-value>
            <description>The URL of the Message Broker to connect to</description>
        </context-param>
        <context-param>
            <param-name>org.apache.activemq.embeddedBroker</param-name>
            <param-value>true</param-value>
            <description>Whether we should include an embedded broker or not</description>
        </context-param>

      <!-- filters -->
      <filter>
        <filter-name>session</filter-name>
        <filter-class>org.apache.activemq.web.SessionFilter</filter-class>
            <async-supported>true</async-supported>
      </filter>
      <filter-mapping>
        <filter-name>session</filter-name>
        <url-pattern>/*</url-pattern>
      </filter-mapping>

      <!-- listener -->
      <listener>
        <listener-class>org.apache.activemq.web.SessionListener</listener-class>
      </listener>

      <!-- servlet mappings -->
        
        <!-- the subscription REST servlet -->
        <servlet>
            <servlet-name>AjaxServlet</servlet-name>
            <servlet-class>org.apache.activemq.web.AjaxServlet</servlet-class>
            <load-on-startup>1</load-on-startup>
            <async-supported>true</async-supported>
      <init-param>
                    <param-name>defaultContentType</param-name>
                    <param-value>application/json</param-value>
            </init-param>         
        </servlet>

        <servlet>
            <servlet-name>MessageServlet</servlet-name>
            <servlet-class>org.apache.activemq.web.MessageServlet</servlet-class>
            <load-on-startup>1</load-on-startup>
            <async-supported>true</async-supported>
      <init-param>
                    <param-name>defaultContentType</param-name>
                    <param-value>application/json</param-value>
            </init-param>         
        </servlet>

        <!-- the queue browse servlet -->
        <servlet>
            <servlet-name>QueueBrowseServlet</servlet-name>
            <servlet-class>org.apache.activemq.web.QueueBrowseServlet</servlet-class>
            <async-supported>true</async-supported>
        </servlet>



        <!-- servlets for the portfolio demo -->
        <servlet>
            <servlet-name>PortfolioPublishServlet</servlet-name>
            <servlet-class>org.apache.activemq.web.PortfolioPublishServlet</servlet-class>
            <load-on-startup>1</load-on-startup>
            <async-supported>true</async-supported>
        </servlet>

      <!-- servlet mappings -->
        <servlet-mapping>
            <servlet-name>AjaxServlet</servlet-name>
            <url-pattern>/amq/*</url-pattern>
        </servlet-mapping>
        
        <servlet-mapping>
            <servlet-name>MessageServlet</servlet-name>
            <url-pattern>/message/*</url-pattern>
        </servlet-mapping>
        
        <servlet-mapping>
            <servlet-name>QueueBrowseServlet</servlet-name>
            <url-pattern>/queueBrowse/*</url-pattern>
        </servlet-mapping>
        
        <servlet-mapping>
            <servlet-name>PortfolioPublishServlet</servlet-name>
            <url-pattern>/portfolioPublish</url-pattern>
        </servlet-mapping>

    </web-app>
