apiVersion: v1
kind: Pod
metadata:
  name: scot
  labels:
    app: scot
  namespace: scot-dev
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: scot
      image: 'image-registry.openshift-image-registry.svc:5000/scot-dev/scot'
      ports:
        - containerPort: 3000
      securityContext:
        runAsUser: 1060
        fsGroup: 2060
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL