apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: scot
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
        - name: scot-prod-init
          configMap:
            name: scot-prod-init
      containers:
        - name: mongodb
          image: 'mongo:4.2.22'
          ports:
            - containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongoadmin
            - name: MONGO_INITDB_DATABASE
              value: scot-prod
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongoadmin
          volumeMounts:
            - name: scot-prod-init
              mountPath: /docker-entrypoint-initdb.d/scot-mongo-db-init.js
              subPath: scot-mongo-db-init.js
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname