apiVersion: v1
kind: Pod
metadata:
  name: stretch
  labels:
    app: scot
  namespace: scot-dev
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: stretch
      image: 'image-registry.openshift-image-registry.svc:5000/scot-dev/scot'
      command: ['/usr/local/bin/hypnotoad']
      args: ['-t', '/opt/scot/bin/stretch.pl']
      securityContext:
        runAsUser: 1060
        fsGroup: 2060
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL